name: haskell-aws-lambda-template
version: 0.1.0.0
category: app
author: Bellroy
maintainer: geeks@bellroy.com
copyright: Bellroy
github: Unisay/haskell-aws-lambda-template
license: NONE

extra-source-files:
  - README.md

ghc-options:
  - "-Wall"
  - "-Wcompat"
  - "-Wincomplete-record-updates"
  - "-Wincomplete-uni-patterns"
  - "-Wredundant-constraints"
  - "-Wtabs"
  - "-fhelpful-errors"

dependencies:
  - base >= 4.7 && < 5
  - aws-lambda-haskell-runtime >= 2.0.1

library:
  source-dirs: src
  exposed-modules:
    - Types
    - Lib
    - Aws.Api.Gateway
  dependencies:
    - aeson
    - aeson-extra
    - aeson-casing
    - amazonka-core
    - bytestring
    - case-insensitive
    - http-types
    - iproute
    - lens
    - modern-uri
    - network
    - protolude
    - text
    - transformers
    - unordered-containers

executables:
  bootstrap:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
      - aeson
      - haskell-aws-lambda-template
      - lens
      - protolude
      - transformers

default-extensions:
  - ApplicativeDo
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - PatternGuards
  - PartialTypeSignatures
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
