org: yuriylazaryev
app: haskell-aws-lambda
service: haskell-serverless
provider:
  name: aws
  runtime: provided
  stage: dev
  region: eu-central-1
  memorySize: 1024
  reservedConcurrency: 10
  timeout: 10
  logRetentionInDays: 14
package:
  individually: true
functions:
  haskell-aws-lambda:
    artifact: build/function.zip
    handler: src/Lib.handler
